language: node_js
cache:
  directories:
    - ~/.npm
  node_js: 
    - '16'
  git:
    depth: 3
  script: 
    - yarn build
  deply: 
    provider: pages,
    edges: true,
    skip-cleanup: true,
    skip-history: true,
    github-token: $GITHUB_TOKEN
    local-dir: dist/
    target-branch: gh-page
    commit_message: "Deply Release"
    on:
      branch: master